language: php

php:
  - 7.1

env:
  global:
    - TEST_BEHAT_PATH: $TRAVIS_BUILD_DIR/tests/behat
    - ILAO_TRAVIS: TRUE

addons:
  chrome: stable

before_install:

  # Update and config composer
  - sudo apt-get update > /dev/null
  - composer self-update

  # Create global path
  - sed -i '1i export PATH="$HOME/.config/composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc

  # Clear Drush version history to download latest.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*

  # Install Drush globally
  - composer global require drush/drush:^8.1

  # Install test dependencies
  - cd $TEST_BEHAT_PATH && composer install
 # - phpenv config-add $TRAVIS_BUILD_DIR/travis.php.ini
  - phpenv rehash

install:

  # Create MySQL Database
  - mysql -e 'create database drupal;'

before_script:
  - cd ~/
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 5
  - wget http://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.1.jar
  - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip && unzip chromedriver_linux64.zip
  - java -jar -Dwebdriver.chrome.driver=chromedriver selenium-server-standalone-3.8.1.jar -log /tmp/webdriver.log > /tmp/webdriver_output.txt 2>&1 &
  - sleep 5

script:

  # Install Drupal Site
  - cd $TRAVIS_BUILD_DIR
  - /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" drush --verbose --yes site-install --db-url="mysql://root:@127.0.0.1/drupal"
  - drush cc all --yes
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

  # Install and configure Apache and PHP-FPM.
#  - sudo apt-get install apache2 libapache2-mod-fastcgi
#  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
#  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
#  - sudo a2enmod rewrite actions fastcgi alias
#  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
#  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
#  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
#  - sudo service apache2 restart

  - cd $TEST_BEHAT_PATH && bin/behat --profile=ci
