#language: php
#sudo: true
#
#php:
#  - 5.6
#
#before_install:
#  - composer self-update
#
#install:
#  - export PATH="$HOME/.composer/vendor/bin:$PATH"
#  - composer global require drush/drush
#  - phpenv rehash
#  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"
#  #- drush --verbose site-install --db-url=mysql://root:@127.0.0.1/drupal --yes
#  # Import config for our pseudo install
#  - cd ./tests/behat
#  - composer install
#
#script:
#  - pwd
#  - ls
#  - bin/behat

language: php

php:
  - 5.6

before_install:

  # Enable $_ENV variables in PHP.
  - echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Ensure that always_populate_raw_post_data PHP setting: Not set to -1 does not happen.
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # Set PHP memory limit to something more realistic.
  - echo "memory_limit=512M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - sudo apt-get update > /dev/null
  - composer self-update
 # - composer global require drush/drush:dev-master
 # - composer global require consolidation/cgr
  - sed -i '1i export PATH="$HOME/.config/composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*
  - composer global require drush/drush:^8.1
  - phpenv rehash

install:

  - drush status
  # Create MySQL Database
  - mysql -e 'create database drupal;'
  - mysql -e 'show databases'
  - cd $TRAVIS_BUILD_DIR
  - drush --verbose --yes site-install install_configure_form.update_notifications.update_status_module=0 --db-url="mysql://root:@127.0.0.1/drupal"

  # Import config for our pseudo install
  - drush --verbose config-import active --yes