language: php

php:
  - 5.6

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update
 # - composer global require drush/drush:dev-master
 # - composer global require consolidation/cgr
  - sed -i '1i export PATH="$HOME/.config/composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer global require drush/drush:dev-master
  - phpenv rehash

install:

  - drush status
  # Create MySQL Database
  - mysql -e 'create database drupal;'
  - mysql -e 'show databases'
  - cd $TRAVIS_BUILD_DIR
  - drush --verbose --yes site-install standard --db-url="mysql://root:@127.0.0.1/drupal"

  # Import config for our pseudo install
  - drush --verbose config-import active --yes

before_script:
  - cd ~/
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - wget http://selenium-release.storage.googleapis.com/3.1/selenium-server-standalone-3.1.0.jar
  - wget https://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && sudo mv chromedriver /usr/bin
  - java -jar -Dwebdriver.chrome.driver=chromedriver selenium-server-standalone-3.1.0.jar > /dev/null &
  - sleep 5

script:

  - cd $TRAVIS_BUILD_DIR/tests/behat && composer install
  - bin/behat