language: php

php:
  - 5.6

env:
  global:
    - TEST_BEHAT_PATH: $TRAVIS_BUILD_DIR/tests/behat
   # - TRAVIS: TRUE

before_install:

  # Update and config composer
  - sudo apt-get update > /dev/null
  - composer self-update

  # Create global path
  - sed -i '1i export PATH="$HOME/.config/composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc

  # Clear Drush version history to download latest.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*

  # Install Drush globally
  - composer global require drush/drush:^8.1

  # Install test dependencies
  - cd $TEST_BEHAT_PATH && composer install
  - phpenv rehash

install:

  # Create MySQL Database
  - mysql -e 'create database drupal;'

  - cd $TRAVIS_BUILD_DIR

  # Install Drupal Site
  - /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" drush --verbose --yes site-install --db-url="mysql://root:@127.0.0.1/drupal"
  - drush cc all --yes

  # Install and configure Apache and PHP-FPM.
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf

  # Enable module
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Restart apache to apply changes
  - sudo service apache2 restart

script:

  # Run Behat test
  - echo "var_dump(getenv()); var_dump($_ENV);" >> $TRAVIS_BUILD_DIR/test.php
  - php $TRAVIS_BUILD_DIR/test.php
  - cd $TEST_BEHAT_PATH && bin/behat --profile=ci