language: php
sudo: true

php:
  - 5.6

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update & /dev/null
  - composer self-update

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:dev-master
  - phpenv rehash
  - mysql -e 'create database drupal;'
  - drush --verbose site-install --db-url=mysql://root:@127.0.0.1/drupal --yes
  # Import config for our pseudo install
  - drush --verbose config-import active --yes
  - cd ./tests/behat
  - composer install
  - cd ../../

script:
  - echo "hello"


